[package]
name = "BUAT"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
gl = "0.14.0"
glfw = "0.61.0"
image = "0.25.9"
imgui-opengl-renderer = "0.12.1"
log = "0.4.29"
log4rs = "1.4.0"
nalgebra-glm = "0.20.0"
regex = "1.12.2"
